name: Build (macOS)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{github.ref}}
        fetch-depth: 1
        submodules: recursive

    - name: Build imgui dylib
      run: |
        cd dll
        bash ./build_imgui_macos.sh
        cd ..

    - name: Commit new libraries
      continue-on-error: true
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}"
        git add lib/*
        git commit -a -m "commit by ${GITHUB_ACTOR} via GitHub Actions"
        git push --force-with-lease -u origin ${{github.ref}}
